### ISSUE TITLE
Set argument type to c_wchar_p: ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by charxhit** [benhoyt/namedmutex#1]
The code has a bug in this line (Windows 11, python 3.9.7):
`_CreateMutex.argtypes = [wintypes.LPCVOID, wintypes.BOOL, wintypes.LPCSTR]`

Creating the lock with the original code will lead to the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\Desktop\scripts\<>.py", line 101, in <module>
    with NamedMutex('get_dir_lock'):
  File "C:\Users\Desktop\scripts\<>.py", line 34, in __init__
    ret = _CreateMutex(None, False, name)
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type
Exception ignored in: <function NamedMutex.close at 0x000001B267BC5550>
Traceback (most recent call last):
  File "C:\Users\Desktop\scripts\<>.py", line 75, in close
    if self.handle is None:
AttributeError: 'NamedMutex' object has no attribute 'handle'
```

To fix the bug, change ln 7 in [namedmutex.py](https://github.com/benhoyt/namedmutex/blob/master/namedmutex.py) to this:
`_CreateMutex.argtypes = [wintypes.LPCVOID, wintypes.BOOL, wintypes.LPCWSTR]`

**Comment by benhoyt** [comment]
I'm actually unsure why this is happening, as I'm using [CreateMutexA](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexa) which should take ASCII `LPCSTR` rather than wide character `LPCWSTR`. However, it definitely is happening across many Python versions -- I just added a "test" across Python 3.5 through 3.10 and they're all failing.

However, I want to update to use [CreateMutexW](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexw) as well to be explicit.

**Comment by benhoyt** [comment]
I've switched to using `CreateMutexW` explicitly in https://github.com/benhoyt/namedmutex/commit/6ce6a87566e47fc8c89553c4db0ed7f30564bda5
